spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: test
    url: jdbc:mysql://localhost:3306/sb_springsecurity_2
    username: root
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

server:
  port: 8080